version: "3"

tasks:
  build-osx:
    aliases:
      - osx
    cmd: sudo darwin-rebuild switch --flake ./
  build-linux:
    aliases:
      - linux
    cmd: echo "Not Yet Implemented"

  test:
    aliases:
      - t
    cmd: nix flake check

  list: task --list-all

  fmt: nix fmt

  default:
    cmds:
      - task: list
