---
version: "3"
tasks:
  default:
    aliases:
      - list
      - l
    desc: List all tasks if none is specified
    cmd: task --list-all
  switch:
    desc: Runs the appropriate switch command for the platform
    aliases:
      - s
    cmds:
      - cmd: task switch:osx
        platforms: [darwin]
      - cmd: task switch:nixos
        platforms: [linux]
  switch:osx:
    desc: Perform osx build and switch
    platforms: [darwin]
    cmd: |
      HOSTNAME=$(hostname -s)
      PASSWORD_PATH="op://Private/${HOSTNAME} Sudo Password/password"
      op run \
        --env-file=<(echo "SUDO_PASSWORD=$(op read "$PASSWORD_PATH")") \
        -- bash -c 'echo "$SUDO_PASSWORD" | sudo -S darwin-rebuild switch --flake ./'
  switch:nixos:
    desc: Perform linux based build
    aliases:
      - linux
    platforms: [linux]
    cmd: sudo nixos-rebuild switch --flake ./
  test:
    desc: Run flake check (now defaults to quick)
    aliases:
      - t
    cmds:
      - task test:quick
  test:quick:
    desc: "Quick syntax and validation checks (30s) - Reports all failures"
    aliases:
      - tq
    cmds:
      - cmd: |
          echo "Running quick validation checks..."
          failed_checks=""

          # Test basic flake validation
          if ! nix flake check --no-build >/dev/null 2>&1; then
            echo "❌ Flake check failed"
            failed_checks="$failed_checks flake-check"
          else
            echo "✅ Flake check passed"
          fi

          # Test Linux configurations
          for config in drlight zero; do
            if nix eval .#nixosConfigurations.$config.config.system.build.toplevel \
              --json >/dev/null 2>&1; then
              echo "✅ NixOS $config configuration valid"
            else
              echo "❌ NixOS $config configuration invalid"
              failed_checks="$failed_checks NixOS:$config"
            fi
          done

          # Test macOS configurations
          for config in wweaver MegamanX; do
            if nix eval .#darwinConfigurations.$config.system \
              --json >/dev/null 2>&1; then
              echo "✅ Darwin $config configuration valid"
            else
              echo "❌ Darwin $config configuration invalid"
              failed_checks="$failed_checks Darwin:$config"
            fi
          done

          # Report all failures
          if [ -n "$failed_checks" ]; then
            echo "❌ Failed checks:$failed_checks"
            exit 1
          else
            echo "✅ All quick validation checks passed"
          fi
  test:full:
    desc: "Full cross-platform verification (5-10min) - Fail fast"
    aliases:
      - tf
    cmds:
      - echo "Universal Cross-Platform Testing Suite"
      - echo "Validating configuration definitions..."
      - nix eval .#nixosConfigurations.drlight.config.system.build.toplevel \
        --json >/dev/null && echo "NixOS drlight configuration valid" || \
        (echo "NixOS drlight configuration invalid" && exit 1)
      - nix eval .#nixosConfigurations.zero.config.system.build.toplevel \
        --json >/dev/null && echo "NixOS zero configuration valid" || \
        (echo "NixOS zero configuration invalid" && exit 1)
      - nix eval .#darwinConfigurations.wweaver.system \
        --json >/dev/null && echo "Darwin wweaver configuration valid" || \
        (echo "Darwin wweaver configuration invalid" && exit 1)
      - nix eval .#darwinConfigurations.MegamanX.system \
        --json >/dev/null && echo "Darwin MegamanX configuration valid" || \
        (echo "Darwin MegamanX configuration invalid" && exit 1)
      - echo "Testing Linux build plans..."
      - nix build .#nixosConfigurations.drlight.config.system.build.toplevel \
        --dry-run --quiet >/dev/null 2>&1 && echo "drlight build plan validated" || \
        (echo "drlight build plan failed" && exit 1)
      - nix build .#nixosConfigurations.zero.config.system.build.toplevel \
        --dry-run --quiet >/dev/null 2>&1 && echo "zero build plan validated" || \
        (echo "zero build plan failed" && exit 1)
      - echo "Testing Darwin evaluations..."
      - nix eval .#darwinConfigurations.wweaver.system \
        --quiet >/dev/null 2>&1 && echo "wweaver evaluation validated" || \
        (echo "wweaver evaluation failed" && exit 1)
      - nix eval .#darwinConfigurations.MegamanX.system \
        --quiet >/dev/null 2>&1 && echo "MegamanX evaluation validated" || \
        (echo "MegamanX evaluation failed" && exit 1)
      - echo "Universal cross-platform testing completed!"
      - echo "Results Summary"
      - echo "   Configuration validation = SUCCESS"
      - echo "   Linux build planning = SUCCESS"
      - echo "   Darwin evaluation = SUCCESS"
      - echo "   Host-agnostic execution = SUCCESS"
  test:darwin-only:
    desc: "Test only Darwin configurations (for Darwin runners)"
    platforms: [darwin]
    cmds:
      - echo "Testing Darwin configurations"
      - echo "=================================="
      - echo "Testing wweaver build plan"
      - cmd: |
          if darwin-rebuild build --flake .#wweaver --dry-run >/dev/null 2>&1; then
            echo "wweaver build plan validated"
          else
            echo "wweaver build plan failed"
            exit 1
          fi
      - echo "Testing MegamanX build plan"
      - cmd: |
          if darwin-rebuild build --flake .#MegamanX --dry-run >/dev/null 2>&1; then
            echo "MegamanX build plan validated"
          else
            echo "MegamanX build plan failed"
            exit 1
          fi
      - echo "All Darwin tests completed"
  test:nixos-only:
    desc: "Test only NixOS configurations (for Linux runners)"
    platforms: [linux]
    cmds:
      - echo "Testing NixOS configurations"
      - echo "================================="
      - echo "Testing drlight build plan"
      - cmd: |
          if nix build .#nixosConfigurations.drlight.config.system.build.toplevel \
              --dry-run --quiet >/dev/null 2>&1; then
            echo "drlight build plan validated"
          else
            echo "drlight build plan failed"
            exit 1
          fi
      - echo "Testing zero build plan"
      - cmd: |
          if nix build .#nixosConfigurations.zero.config.system.build.toplevel \
              --dry-run --quiet >/dev/null 2>&1; then
            echo "zero build plan validated"
          else
            echo "zero build plan failed"
            exit 1
          fi
      - echo "All NixOS tests completed"
  build:
    desc: build all configurations
    aliases:
      - b
    cmds:
      - echo "🔍 building flake configurations..."
      - task: build:darwin
      - task: build:nixos
      - echo "✅ All configurations (NixOS and Darwin) validated successfully"
  build:darwin:
    desc: build all Darwin (macOS) configurations
    cmds:
      - echo "🍎 building Darwin configurations..."
      # - task: build:darwin:will-stride-mbp
      - task: build:darwin:megamanx
      - echo "✅ All Darwin configurations validated successfully"
  build:nixos:
    desc: build all NixOS configurations
    cmds:
      - echo "🐧 building NixOS configurations..."
      - task: build:nixos:drlight
      # - task: build:nixos:zero
      - echo "✅ All NixOS configurations validated successfully"
  quality:
    desc: Run all code quality checks.
    aliases:
      - q
    cmds:
      - devenv test
  dev:
    desc: Enter development shell with all tools available.
    aliases:
      - d
    cmd: devenv shell
  devenv:update:
    desc: Update devenv lock file.
    cmd: devenv update
  init:
    desc: Initial setup commands
    cmds:
      - sudo nix run nix-darwin/master#darwin-rebuild -- switch --flake ./
  git:set-remote-ssh:
    desc: Switch
    cmds:
      - git remote -v
      - git remote set-url origin git@github.com:funkymonkeymonk/nix.git
      - git remote -v
  git:set-remote-https:
    desc: Switch
    cmds:
      - git remote -v
      - git remote set-url origin https://github.com/funkymonkeymonk/nix.git
      - git remote -v
  flake:update:
    desc: Update the nix flake to latest versions
    cmd: nix flake update
