version: "3"

tasks:
  default:
    desc: List all tasks if none is specified
    aliases:
      - l
      - list
    cmd: task --list-all

  switch:
    desc: Runs the appropriate switch command for the platform
    aliases:
      - s
    cmds:
      - cmd: task switch:osx
        platforms: [darwin]
      - cmd: task switch:nixos
        platforms: [linux]

  test:quick:
    desc: "Quick syntax and validation checks (30s) - Reports all failures"
    aliases:
      - tq
    cmds:
      - task: test:quick
    test:quick:
      desc: "Quick syntax and validation checks (30s) - Reports all failures"
      aliases:
        - tq
      cmds:
        - cmd: |
            echo "Running quick validation checks..."
            failed_checks=""

            # Test basic flake validation
            echo "🔍 Checking flake structure and dependencies..."
            if ! nix flake check --no-build >/dev/null 2>&1; then
              echo "❌ Flake check failed"
              echo "🐛 Running flake check with verbose output for debugging:"
              nix flake check --no-build --show-trace
              failed_checks="$failed_checks flake-check"
            else
              echo "✅ Flake check passed"
            fi

            # Test Linux configurations
            for config in drlight zero; do
              echo "🐧 Validating NixOS $config configuration..."
              if nix eval .#nixosConfigurations.$config.config.system.build.toplevel \
                --json >/dev/null 2>&1; then
                echo "✅ NixOS $config configuration valid"
              else
                echo "❌ NixOS $config configuration invalid"
                echo "🐛 Running flake check with verbose output for debugging:"
                nix eval .#nixosConfigurations.$config.config.system.build.toplevel \
                  --json --show-trace
                failed_checks="$failed_checks NixOS:$config"
              fi
            done

            # Test macOS configurations
            for config in wweaver MegamanX; do
              echo "🍎 Validating Darwin $config configuration..."
              if nix eval .#darwinConfigurations.$config.system \
                --json >/dev/null 2>&1; then
                echo "✅ Darwin $config configuration valid"
              else
                echo "❌ Darwin $config configuration invalid"
                echo "🐛 Running flake check with verbose output for debugging:"
                nix eval .#darwinConfigurations.$config.system \
                  --json --show-trace
                failed_checks="$failed_checks Darwin:$config"
              fi
            done

            # Report all failures
            if [ -n "$failed_checks" ]; then
              echo ""
              echo "💀 QUICK VALIDATION FAILED"
              echo "Failed checks:$failed_checks"
              echo ""
              echo "🔧 To debug individual issues:"
              for check in $failed_checks; do
                case $check in
                  "flake-check")
                    echo "  - Run: nix flake check --no-build --show-trace"
                    ;;
                  "NixOS:"*)
                    config=${check#NixOS:}
                    echo "  - Run: nix eval \\"
                    echo "             .#nixosConfigurations.$config.config.system.build.topleft \\"
                    echo "             --json --show-trace"
                    ;;
                  "Darwin:"*)
                    config=${check#Darwin:}
                    echo "  - Run: nix eval \\"
                    echo "             .#darwinConfigurations.$config.system \\"
                    echo "             --json --show-trace"
                    ;;
                esac
              done
              exit 1
            else
              echo "✅ All quick validation checks passed"
            fi

  build:oci-image:
    desc: "Build OCI image for local use"
    vars:
      IMAGE_NAME:
        sh: echo "${IMAGE_NAME:-app-image}"
      IMAGE_TAG:
        sh: echo "${IMAGE_TAG:-latest}"
      REGISTRY:
        sh: echo "${IMAGE_TAG:-localhost:5000}}"
    cmds:
      - task: build:oci-image