# email-backup module: Immutable encrypted email backups
#
# Pipeline:
#   Gmail → mbsync (pull-only) → local Maildir (staging)
#                                       ↓
#                                 notmuch index (searchable)
#                                       ↓
#                                 restic backup → encrypted repo (immutable)
#
# The agent never touches this pipeline. It runs on a timer and produces
# an append-only backup that you can search and restore from if an agent
# does something wrong.
#
# Authentication:
# - mbsync: Gmail App Password via PassCmd (stored in ~/.mbsync-passwd or 1Password)
# - restic: Password in ~/.config/email-backup/restic-password
#
# Recovery:
#   email-backup-restore list                        # List snapshots
#   email-backup-restore mount /tmp/restore          # Mount a snapshot
#   email-backup-restore search "from:important@"    # Search backup via notmuch
{
  config,
  lib,
  pkgs,
  userConfig,
  osConfig ? null,
  ...
}:
with lib; let
  cfg =
    osConfig.myConfig.email-backup
    or config.myConfig.email-backup
    or {};
  enabled = cfg.enable or false;
  isDarwin =
    if osConfig != null
    then osConfig.myConfig.isDarwin or false
    else pkgs.stdenv.hostPlatform.isDarwin;

  # Config values
  accountName = cfg.accountName or "gmail";
  imapHost = cfg.imapHost or "imap.gmail.com";
  imapPort = toString (cfg.imapPort or 993);
  username = cfg.username or "";
  backupInterval = cfg.backupInterval or 3600;
  maildir = cfg.maildir or ".mail-backup";
  resticRepo = cfg.resticRepo or ".local/share/email-backup/restic-repo";
  resticPasswordFile = cfg.resticPasswordFile or ".config/email-backup/restic-password";
  retentionDays = cfg.retentionDays or 365;
  newTag = cfg.notmuchTags.new or "new";
  excludeTags = cfg.notmuchTags.exclude or ["deleted" "spam"];
  userEmail = userConfig.email or "";

  # Paths (use $HOME for runtime expansion in scripts)
  maildirPath = "$HOME/${maildir}";
  accountMaildir = "${maildirPath}/${accountName}";
  resticRepoPath = "$HOME/${resticRepo}";
  resticPasswordPath = "$HOME/${resticPasswordFile}";

  certPath =
    if isDarwin
    then "/etc/ssl/cert.pem"
    else "/etc/ssl/certs/ca-certificates.crt";

  servicePath =
    if isDarwin
    then "/Users/${username}/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/bin:/bin"
    else "$HOME/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/bin:/bin";

  # mbsync configuration — pull-only, read-only backup
  mbsyncrcContent = ''
    # mbsync configuration for email backup
    # Generated by nix email-backup module
    # PULL-ONLY — this never modifies Gmail
    #
    # Authentication setup:
    #   echo 'your-app-password' > ~/.mbsync-passwd && chmod 600 ~/.mbsync-passwd
    #
    # For 1Password:
    #   Replace PassCmd with: PassCmd "op read 'op://Private/Gmail App Password/password'"

    IMAPAccount ${accountName}
    Host ${imapHost}
    Port ${imapPort}
    User ${userEmail}
    PassCmd "cat ~/.mbsync-passwd"
    SSLType IMAPS
    CertificateFile ${certPath}

    IMAPStore ${accountName}-remote
    Account ${accountName}

    MaildirStore ${accountName}-local
    SubFolders Verbatim
    Path ${accountMaildir}/
    Inbox ${accountMaildir}/Inbox

    Channel ${accountName}
    Far :${accountName}-remote:
    Near :${accountName}-local:
    Patterns *
    Create Near
    Expunge None
    SyncState *
    Sync Pull
  '';

  # Notmuch config shared between email-backup-setup's first-run heredoc
  # and the standalone .notmuch-config-backup file written below.
  notmuchConfigContent = ''
    [database]
    path=${maildirPath}

    [user]
    name=${userConfig.fullName or userConfig.name or ""}
    primary_email=${userEmail}

    [new]
    tags=${newTag}
    ignore=.mbsyncstate;.uidvalidity

    [search]
    exclude_tags=${builtins.concatStringsSep ";" excludeTags}

    [maildir]
    synchronize_flags=true
  '';

  # Setup script — initializes restic repo, notmuch db, and mbsync config.
  # Script bodies below live in email-backup/*.sh so they get proper bash
  # syntax highlighting and can be shellchecked directly.
  emailBackupSetupContent =
    lib.replaceStrings
    ["__MAILDIR_PATH__" "__RESTIC_REPO_PATH__" "__RESTIC_PASSWORD_PATH__" "__NOTMUCH_CONFIG__"]
    [maildirPath resticRepoPath resticPasswordPath (lib.removeSuffix "\n" notmuchConfigContent)]
    (builtins.readFile ./email-backup/email-backup-setup.sh);

  # Main backup script
  emailBackupContent =
    lib.replaceStrings
    ["__MAILDIR_PATH__" "__ACCOUNT_MAILDIR__" "__RESTIC_REPO_PATH__" "__RESTIC_PASSWORD_PATH__" "__ACCOUNT_NAME__" "__RETENTION_DAYS__"]
    [maildirPath accountMaildir resticRepoPath resticPasswordPath accountName (toString retentionDays)]
    (builtins.readFile ./email-backup/email-backup.sh);

  # Restore / search script
  emailBackupRestoreContent =
    lib.replaceStrings
    ["__MAILDIR_PATH__" "__RESTIC_REPO_PATH__" "__RESTIC_PASSWORD_PATH__"]
    [maildirPath resticRepoPath resticPasswordPath]
    (builtins.readFile ./email-backup/email-backup-restore.sh);

  # Status script
  emailBackupStatusContent =
    lib.replaceStrings
    ["__MAILDIR_PATH__" "__RESTIC_REPO_PATH__" "__RESTIC_PASSWORD_PATH__" "__BACKUP_INTERVAL_MINUTES__" "__RETENTION_DAYS__"]
    [maildirPath resticRepoPath resticPasswordPath (toString (backupInterval / 60)) (toString retentionDays)]
    (builtins.readFile ./email-backup/email-backup-status.sh);
in {
  config = mkIf enabled {
    assertions = [
      {
        assertion = !isDarwin || username != "";
        message = "email-backup.username is required on Darwin for launchd services";
      }
      {
        assertion = userEmail != "";
        message = "email-backup requires a user email to be configured (myConfig.users[].email)";
      }
    ];

    # Install scripts
    home.packages = [
      (pkgs.writeShellScriptBin "email-backup" emailBackupContent)
      (pkgs.writeShellScriptBin "email-backup-setup" emailBackupSetupContent)
      (pkgs.writeShellScriptBin "email-backup-restore" emailBackupRestoreContent)
      (pkgs.writeShellScriptBin "email-backup-status" emailBackupStatusContent)
    ];

    # Write mbsync config (separate from any agent mbsyncrc)
    home.file.".mbsyncrc-backup".text = mbsyncrcContent;

    # Write notmuch config for backup
    home.file.".notmuch-config-backup".text = notmuchConfigContent;

    # launchd agent for macOS
    launchd.agents = mkIf isDarwin {
      email-backup = {
        enable = true;
        config = {
          ProgramArguments = ["${pkgs.writeShellScript "email-backup" emailBackupContent}"];
          StartInterval = backupInterval;
          RunAtLoad = false;
          StandardOutPath = "/tmp/email-backup-launchd.log";
          StandardErrorPath = "/tmp/email-backup-launchd.err";
          EnvironmentVariables = {
            HOME = "/Users/${username}";
            PATH = servicePath;
            SSL_CERT_FILE = certPath;
          };
        };
      };
    };

    # systemd user service for Linux
    systemd.user.services = mkIf (!isDarwin) {
      email-backup = {
        Unit = {
          Description = "Email backup (mbsync pull + restic snapshot)";
          After = ["network-online.target"];
        };
        Service = {
          Type = "oneshot";
          ExecStart = "${pkgs.writeShellScript "email-backup" emailBackupContent}";
          Environment = [
            "HOME=%h"
            "PATH=%h/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/bin:/bin"
            "SSL_CERT_FILE=${certPath}"
          ];
        };
      };
    };

    systemd.user.timers = mkIf (!isDarwin) {
      email-backup = {
        Unit = {
          Description = "Periodic email backup timer";
        };
        Timer = {
          OnUnitActiveSec = "${toString backupInterval}s";
          OnBootSec = "10min";
          Persistent = true;
        };
        Install = {
          WantedBy = ["timers.target"];
        };
      };
    };
  };
}
