# Hammerspoon configuration for trackpad gesture handling
# This module configures Hammerspoon to detect trackpad swipe gestures
# and use them to switch AeroSpace workspaces
{
  lib,
  config,
  ...
}:
with lib; let
  cfg = config.programs.hammerspoon;
  aerospaceSwipeConfig = ''
    -- AeroSpace workspace switching via Ctrl + two-finger horizontal scroll
    -- Hold Ctrl and scroll left/right on trackpad to switch workspaces

    local log = hs.logger.new('workspace', 'info')

    -- Track state
    local lastSwitchTime = 0
    local switchCooldown = 0.3 -- seconds between switches

    -- Create an eventtap for scroll wheel events
    local scrollTap = hs.eventtap.new({hs.eventtap.event.types.scrollWheel}, function(event)
        -- Check if Ctrl is held
        if not event:getFlags().ctrl then
            return false
        end

        -- Cooldown check
        local now = hs.timer.secondsSinceEpoch()
        if (now - lastSwitchTime) < switchCooldown then
            return true
        end

        -- Get horizontal scroll delta
        local deltaX = event:getProperty(hs.eventtap.event.properties.scrollWheelEventDeltaAxis2)

        -- Only trigger on significant horizontal movement
        if math.abs(deltaX) < 3 then
            return true
        end

        lastSwitchTime = now

        local dir = deltaX > 0 and "prev" or "next"
        os.execute("/run/current-system/sw/bin/aerospace workspace --wrap-around --no-stdin " .. dir .. " &")

        return true -- consume the event
    end)

    scrollTap:start()
    log.i("AeroSpace: Ctrl + scroll left/right to switch workspaces")
  '';
in {
  options.programs.hammerspoon = {
    enable = mkEnableOption "Hammerspoon configuration";

    enableAerospaceSwipes = mkOption {
      type = types.bool;
      default = true;
      description = "Enable trackpad swipe gestures to switch AeroSpace workspaces";
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Additional Lua configuration for Hammerspoon";
    };
  };

  config = mkIf cfg.enable {
    # Create the Hammerspoon init.lua configuration
    home.file.".hammerspoon/init.lua".text = ''
      -- Hammerspoon configuration
      -- Generated by nix-darwin home-manager

      -- Reload config notification
      hs.alert.show("Hammerspoon Config Loaded")

      ${optionalString cfg.enableAerospaceSwipes aerospaceSwipeConfig}

      ${cfg.extraConfig}
    '';

    # Ensure the .hammerspoon directory exists
    home.file.".hammerspoon/.keep".text = "";
  };
}
